apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-java
  labels:
    app: factorial-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorial-java
  template:
    metadata:
      labels:
        app: factorial-java
    spec:
      containers:
      - name: factorial-java
        image: <docker-username>/factorial-java:latest
        stdin: true
        tty: true
